### PR TITLE
Don't leave fans running on stop

### PR DESCRIPTION
**Pull request by Sonderstorch**
The ported firmware still has the Anycubic upstream bug of leaving the object cooler fan running if the print is stopped manually. I'd propose to copy-over the lines from ultralcd.cpp.

### CODE REVIEW

**Comment by Sonderstorch** [comment]
I have to add that this is untested yet. It compiles, though.

**Review by derhopp — APPROVED** [review]
This change will be included.  Thank you!

**Comment by derhopp** [comment]
I have approved the dual Z-stop change, because my system is now V2 compatible.

**Comment by Sonderstorch** [comment]
Thanks! Meanwhile I also tested on my machine (it's a V2 mega) that the changes in PausePrint() actually do stop the part cooler when aborting the print on the TFT without any adverse side effects as far as I observed.

**Pull request merged**
