### PR TITLE
Create Configuration-MegaUltrabase.h

### PR DESCRIPTION
**Pull request by bartolomeus**
This is an attempt to create a Config file for the i3 Mega Ultrabase (dual endstops, no probe), with some additional changes:
- enabled Manual Mesh Bed Levelling: http://marlinfw.org/docs/gcode/G029-mbl.html
- lowered default acceleration settings.

To do:
- Enable bed pid & add pid values

### CODE REVIEW

**Comment by derhopp** [comment]
Thanks for the patch... should we better put it to example_configurations/Anycubic/MegaUltrabase/ ?

**Comment by bartolomeus** [comment]
Yeah, that would be an option. Maybe make a readme so people can find the
file?

Op 1 feb. 2018 20:35 schreef "derhopp" <notifications@github.com>:

Thanks for the patch... should we better put it to
example_configurations/Anycubic/MegaUltrabase/
?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/derhopp/Marlin-with-Anycubic-i3-Mega-TFT/pull/4#issuecomment-362377405>,
or mute the thread

**Comment by derhopp** [comment]
Okay, could you put it there.

I will make Anycubic Mega specific part in the Marlin Readme.

**Comment by derhopp** [comment]
I have just added your Configuration.h to the example area.

**Comment by bartolomeus** [comment]
Ok thanks. I wasn't with a pc nearby.

Op 1 feb. 2018 21:23 schreef "derhopp" <notifications@github.com>:

**Pull request closed without merging**
