### PR TITLE
Update Configuration.h

### PR DESCRIPTION
**Pull request by bartolomeus**
Drecreased max temp for stock hotend
Lowered default acceleration.

### CODE REVIEW

**Comment by Elehiggle** [comment]
Any particular reason to decrease the acceleration? The new Anycubic official open source Marlin at https://github.com/ANYCUBIC-3D/I3-MEGA still has those 3000 values. I must say I ran into resonance issues due to too fast speeds and this will probably help a bit, but I thought I had to generally decrease the speed.

**Comment by derhopp** [comment]
To high acceleration causes the mainly stress to belts and stepper drivers but it is also responsible effect you ran into.  The stock printer is not made for that.

**Comment by Guex** [comment]
i disagree to lower HEATER_0_MAXTEMP to from 285 to 245, as it will turn off the heating way too early. The default firmware allows to heat up to 260 and i have ABS filament with vendor recommendation to print @250. i'd recommend to change it back to 285 like ANYCUBIC had.

**Comment by derhopp** [comment]
As long as you use the stock printer I do not recommend these high temperatures because of the PTFE insert in the hotend. They start to deform at 250°C.  Thus, if someone wants to print with higher temperatures, it is better to raise it intentionally.  Just my opinion.

**Comment by newPOPE** [comment]
Agree with @derhopp, you can build it with own configuration (as I did). 

BTW: I like this repo, but what was a reason for disable issues? Issues are good place for negotiations.

**Comment by derhopp** [comment]
I didn't disable issues intentionally.  (:   They are now enabled.

**Pull request merged**
